# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kamay
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: su-ph-le-te-is-py-ap
# "service" is the name of this project. This will also be added to your AWS resource names.
service: su-ph-le-te-is-py

provider:
  name: aws
  runtime: python3.12
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lex:*
      Resource: '*'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: telegram-webhook
          method: post
          cors: true

plugins:
  - serverless-pydeps
